### ISSUE TITLE
Adicionar vídeos

### ISSUE THREAD

**Issue by devcaiada** [iisrax/desafio-github-markdown#3]
Poderia adicionar vídeos ao seu README. O Markdown não permite, mas pode colocar uma foto com um link para o vídeo no youtube.

Eles não podem ser adicionados diretamente, mas você pode adicionar uma imagem com um link para o vídeo como este:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=YOUTUBE_VIDEO_ID_HERE
" target="_blank"><img src="http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg" 
alt="Texto ALT da imagem aqui" width="240" height="180" border="10" /></a>

**Comment by iisrax** [comment]
Olá, @devcaiada, tudo bem?

Poderia me explicar de uma maneira diferente a sua melhoria para o meu README? Porque, se entendi, o README já atende esses parâmetros, tanto que o link dos vídeos do YouTube está logo abaixo das imagens que o representam.
